#!/bin/sh
### BEGIN INIT INFO
# Provides:          SiemensPDE
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop/Restart SiemensPDE Service
# Description:       Verwaltet den SiemensPDE-Dienst.
### END INIT INFO

SERVICE="SiemensPDE"
APPNAME="Serial2Siemens"
JAR_PATH="/home/pi/deploy"
LOGFILE="/home/logs/SiemensPDE.log"

# Überprüft, ob der Dienst läuft
check_status() {
    if pgrep -x "$SERVICE" >/dev/null; then
        echo "$SERVICE is running"
    else
        echo "$SERVICE is stopped"
    fi
}

# Start des Dienstes
start() {
    echo "Starting $SERVICE..."
    if pgrep -x "$SERVICE" >/dev/null; then
        echo "$SERVICE is already running."
    else
        cd $JAR_PATH
        java -Dprogram.name=$SERVICE -jar $SERVICE.jar $APPNAME >> $LOGFILE 2>&1 &
        sleep 2
        check_status
    fi
}

# Stoppen des Dienstes
stop() {
    echo "Stopping $SERVICE..."
    if pgrep -x "$SERVICE" >/dev/null; then
        sudo pkill -f "$SERVICE"
        echo "$SERVICE has been stopped."
    else
        echo "$SERVICE is not running."
    fi
}

# Neustarten des Dienstes
restart() {
    echo "Restarting $SERVICE..."
    stop
    sleep 2
    start
}

# Hauptsteuerung für das Skript
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        check_status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
