#!/bin/sh
logfile=/home/logs/cron.log
SERVICE="SiemensPDE"

# Makes sure that the SiemensPDE service keeps running
if [ $(pgrep -f -c $SERVICE) -ge 1 ]; then
    echo "$(date) SiemensPDE is running" >> $logfile
else
    echo "$(date) SiemensPDE is dead. Bringing it back to life." >> $logfile
    /etc/init.d/EasyBox-SiemensPDE restart
fi
